### PR TITLE
Replace setup.py with pyproject.toml and automate new releases.

### PR DESCRIPTION
**Pull request by moigagoo**

### CODE REVIEW

**Comment by moigagoo** [comment]
I've added Travis CI, but I see you're using this thing called Netlify. Should I remove .travis.ci and write a config for Netlify? I can't see any config so far in the repo.

**Comment by moigagoo** [comment]
It seems like Netlify is configured to build and deploy the docs on each commit but the config is not here in the repo. We can place the script to build and upload the docs in .travis.ci, like I do in cliar: https://github.com/moigagoo/cliar/blob/develop/.travis.yml#L14

I'm deploying to GitHub pages, but you can run any deploy script: https://github.com/moigagoo/cliar/blob/develop/.travis.yml#L22

**Comment by moigagoo** [comment]
The main motivation for the change is that Poetry allows to dramatically reduce packaging boilerplate. It makes it easy for developers to install the package in an isolated environment. Read more at https://poetry.eustace.io/ to learn about the benefits of Poetry.

**Comment by notpushkin** [comment]
I'm actually using Poetry myself on recent projects :)

There are some advantages in Netlify building the docs, like the [deploy previews][1] (can be configured with Travis as well in theory, but here it works out of the box). I've added a config, although it is quite complicated as there is no first-class Poetry support on Netlify yet (https://github.com/netlify/build-image/issues/221, I think I'll work on a PR some day).

[1]: https://www.netlify.com/docs/continuous-deployment/#definitions

Looking into the Travis integration now!

**Comment by moigagoo** [comment]
> I'm actually using Poetry myself on recent projects :)

Yay, great choice :-)

> Looking into the Travis integration now!

I see there's a failed build: https://travis-ci.org/notpushkin/mkdocs-alabaster

Note that Travis has split into travis-ci.org and travis-ci.com. AFAIU .org is deprecated and .com is the thing to use. So you should switch the project to travis-ci.com. I know it's silly, right :-)

**Comment by notpushkin** [comment]
Oops! Apparently we'll have to stick to .org for now: it says that [we need to migrate](https://travis-ci.com/notpushkin/mkdocs-alabaster) and [that this is a manual process right now](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg). :')

**Comment by moigagoo** [comment]
🤦‍♂️OMG Travis what r u doing STAHP

Anyway, we could stick to Netlify for documentation deployment and Travis for PyPI deployment ¯\_(ツ)_/¯

Feel free to merge if you're OK with the PR, or leave a comment for me to fix.

**Comment by notpushkin** [comment]
I don't see an obvious (if any at all) way to test Travis config apart from trying to merge it and add a new tag, so let's go for it!

**Pull request merged**
